// ============ CONFIGURATION ============
const CONFIG = {
    focusNumber: parseInt(localStorage.getItem('focusNumber')) || 7,
    colors: {pink:'#FF1493', orange:'#FF6600', green:'#00CC66', blue:'#0099FF'},
    categories: {
        animals: ['🐱','🐶','🐰','🐻','🐸','🐷','🐮','🦁','🐯','🐨'],
        fruits: ['🍎','🍊','🍇','🍓','🍌','🍉','🍑','🍒','🥝','🍋'],
        vegetables: ['🥕','🥦','🌽','🥒','🍆','🥬','🧅','🧄','🥔','🍅'],
        vehicles: ['🚗','🚌','🚁','🚂','🚀','🚲','🛵','🚒','✈️','🚢'],
        electronics: ['📱','💻','🖥️','📺','🎮','⌚','📷','🎧','🖨️','💡'],
        furniture: ['🛋️','🪑','🛏️','🚪','🪞','🖼️','🧸','🛁','🚿','🪴'],
        shoes: ['👟','👠','👢','👡','🥾','👞','🩴','⛸️','🛼','🎿'],
        clothes: ['👕','👖','👗','👔','🧥','👙','🩳','🧦','🧣','👒'],
        food: ['🍕','🍔','🍦','🍩','🧁','🍪','🌮','🍟','🥤','🍿'],
        dessert: ['🍰','🎂','🧁','🍫','🍬','🍭','🍡','🥧','🍮','🍨'],
        sky: ['⭐','🌙','☀️','🌈','☁️','⚡','🌟','💫','🌤️','🌸'],
        school: ['✏️','📚','🖍️','📏','✂️','🎒','📝','🖊️','📐','🎨'],
        sports: ['⚽','🏀','🎾','🏈','⚾','🏐','🎱','🏓','🥊','🏋️'],
        weather: ['🌧️','❄️','🌪️','🌊','🔥','💨','🌡️','☔','⛄','🌻'],
        insects: ['🦋','🐝','🐞','🐛','🦗','🐜','🪲','🦟','🪳','🕷️'],
        ocean: ['🐟','🐠','🦈','🐙','🦑','🦀','🐚','🐳','🦭','🪸'],
        birds: ['🐦','🦅','🦆','🦉','🐧','🦜','🕊️','🦢','🦩','🐔'],
        flowers: ['🌸','🌷','🌹','🌺','🌻','💐','🌼','🪻','🪷','🌱'],
        tools: ['🔨','🪛','🔧','🪚','🛠️','⚙️','🔩','📎','🧲','🪜'],
        music: ['🎵','🎸','🎹','🥁','🎺','🎷','🎻','🪘','🎤','🎼'],
        kitchen: ['🍳','🥄','🍴','🔪','🥣','🫖','☕','🍶','🧂','🥡'],
        space: ['🚀','🛸','👽','🌍','🪐','☄️','🌕','👨‍🚀','🛰️','🔭'],
        farm: ['🐄','🐖','🐑','🐓','🐴','🦃','🥚','🌾','🚜','🐐'],
        faces: ['😀','😂','😍','😎','🥳','😴','🤔','😱','🤗','🥰'],
        hands: ['👍','👏','🙌','👋','✌️','🤞','👊','🤝','💪','🖐️']
    },
    twoLetterWords: ['IN','AT','ON','OF','SO','TO','GO','UP','ME','IT'],
    threeLetterWords: ['CAT','DOG','SUN','BIG','RED','RUN','SIT','HAT','PEN','CUP'],
    traceUppercase: ['A','B','C','D','E'],
    traceLowercase: ['a','b','c','d','e'],
    traceNumbers: ['1','2','3','4','5','6','7']
};

let currentAnswers = [];

// Urdu Letters (isolated forms with harakat)
const URDU_LETTERS = [
    {letter:'ا', name:'alif', fatha:'اَ', kasra:'اِ', damma:'اُ', sf:'a', sk:'i', sd:'u'},
    {letter:'ب', name:'bay', fatha:'بَ', kasra:'بِ', damma:'بُ', sf:'ba', sk:'bi', sd:'bu'},
    {letter:'پ', name:'pay', fatha:'پَ', kasra:'پِ', damma:'پُ', sf:'pa', sk:'pi', sd:'pu'},
    {letter:'ت', name:'tay', fatha:'تَ', kasra:'تِ', damma:'تُ', sf:'ta', sk:'ti', sd:'tu'},
    {letter:'ٹ', name:'ttay', fatha:'ٹَ', kasra:'ٹِ', damma:'ٹُ', sf:'tta', sk:'tti', sd:'ttu'},
    {letter:'ث', name:'say', fatha:'ثَ', kasra:'ثِ', damma:'ثُ', sf:'sa', sk:'si', sd:'su'},
    {letter:'ج', name:'jeem', fatha:'جَ', kasra:'جِ', damma:'جُ', sf:'ja', sk:'ji', sd:'ju'},
    {letter:'چ', name:'chay', fatha:'چَ', kasra:'چِ', damma:'چُ', sf:'cha', sk:'chi', sd:'chu'},
    {letter:'ح', name:'hey', fatha:'حَ', kasra:'حِ', damma:'حُ', sf:'ha', sk:'hi', sd:'hu'},
    {letter:'خ', name:'khay', fatha:'خَ', kasra:'خِ', damma:'خُ', sf:'kha', sk:'khi', sd:'khu'},
    {letter:'د', name:'daal', fatha:'دَ', kasra:'دِ', damma:'دُ', sf:'da', sk:'di', sd:'du'},
    {letter:'ڈ', name:'ddaal', fatha:'ڈَ', kasra:'ڈِ', damma:'ڈُ', sf:'dda', sk:'ddi', sd:'ddu'},
    {letter:'ذ', name:'zaal', fatha:'ذَ', kasra:'ذِ', damma:'ذُ', sf:'za', sk:'zi', sd:'zu'},
    {letter:'ر', name:'ray', fatha:'رَ', kasra:'رِ', damma:'رُ', sf:'ra', sk:'ri', sd:'ru'},
    {letter:'ڑ', name:'rray', fatha:'ڑَ', kasra:'ڑِ', damma:'ڑُ', sf:'rra', sk:'rri', sd:'rru'},
    {letter:'ز', name:'zay', fatha:'زَ', kasra:'زِ', damma:'زُ', sf:'za', sk:'zi', sd:'zu'},
    {letter:'ژ', name:'zhay', fatha:'ژَ', kasra:'ژِ', damma:'ژُ', sf:'zha', sk:'zhi', sd:'zhu'},
    {letter:'س', name:'seen', fatha:'سَ', kasra:'سِ', damma:'سُ', sf:'sa', sk:'si', sd:'su'},
    {letter:'ش', name:'sheen', fatha:'شَ', kasra:'شِ', damma:'شُ', sf:'sha', sk:'shi', sd:'shu'},
    {letter:'ص', name:'suad', fatha:'صَ', kasra:'صِ', damma:'صُ', sf:'sa', sk:'si', sd:'su'},
    {letter:'ض', name:'zuad', fatha:'ضَ', kasra:'ضِ', damma:'ضُ', sf:'za', sk:'zi', sd:'zu'},
    {letter:'ط', name:'toy', fatha:'طَ', kasra:'طِ', damma:'طُ', sf:'ta', sk:'ti', sd:'tu'},
    {letter:'ظ', name:'zoy', fatha:'ظَ', kasra:'ظِ', damma:'ظُ', sf:'za', sk:'zi', sd:'zu'},
    {letter:'ع', name:'ain', fatha:'عَ', kasra:'عِ', damma:'عُ', sf:'a', sk:'i', sd:'u'},
    {letter:'غ', name:'ghain', fatha:'غَ', kasra:'غِ', damma:'غُ', sf:'gha', sk:'ghi', sd:'ghu'},
    {letter:'ف', name:'fay', fatha:'فَ', kasra:'فِ', damma:'فُ', sf:'fa', sk:'fi', sd:'fu'},
    {letter:'ق', name:'qaaf', fatha:'قَ', kasra:'قِ', damma:'قُ', sf:'qa', sk:'qi', sd:'qu'},
    {letter:'ک', name:'kaaf', fatha:'کَ', kasra:'کِ', damma:'کُ', sf:'ka', sk:'ki', sd:'ku'},
    {letter:'گ', name:'gaaf', fatha:'گَ', kasra:'گِ', damma:'گُ', sf:'ga', sk:'gi', sd:'gu'},
    {letter:'ل', name:'laam', fatha:'لَ', kasra:'لِ', damma:'لُ', sf:'la', sk:'li', sd:'lu'},
    {letter:'م', name:'meem', fatha:'مَ', kasra:'مِ', damma:'مُ', sf:'ma', sk:'mi', sd:'mu'},
    {letter:'ن', name:'noon', fatha:'نَ', kasra:'نِ', damma:'نُ', sf:'na', sk:'ni', sd:'nu'},
    {letter:'ں', name:'noon ghunna', fatha:'ں', kasra:'ں', damma:'ں', sf:'n', sk:'n', sd:'n'},
    {letter:'و', name:'wao', fatha:'وَ', kasra:'وِ', damma:'وُ', sf:'wa', sk:'wi', sd:'wu'},
    {letter:'ہ', name:'hey', fatha:'ہَ', kasra:'ہِ', damma:'ہُ', sf:'ha', sk:'hi', sd:'hu'},
    {letter:'ھ', name:'dochashmee hey', fatha:'ھ', kasra:'ھ', damma:'ھ', sf:'h', sk:'h', sd:'h'},
    {letter:'ی', name:'yay', fatha:'یَ', kasra:'یِ', damma:'یُ', sf:'ya', sk:'yi', sd:'yu'},
    {letter:'ے', name:'bari yay', fatha:'ے', kasra:'ے', damma:'ے', sf:'ay', sk:'ay', sd:'ay'}
];

const URDU_WORDS = [
    {word:'اَب', sound:'ab', meaning:'now'},
    {word:'اِس', sound:'is', meaning:'this'},
    {word:'جَب', sound:'jab', meaning:'when'},
    {word:'سَب', sound:'sab', meaning:'all'},
    {word:'دِل', sound:'dil', meaning:'heart'},
    {word:'گُل', sound:'gul', meaning:'flower'},
    {word:'نَل', sound:'nal', meaning:'tap'},
    {word:'کَل', sound:'kal', meaning:'tomorrow'},
    {word:'پَر', sound:'par', meaning:'on/wing'},
    {word:'دو', sound:'do', meaning:'two'},
    {word:'تُو', sound:'tu', meaning:'you'},
    {word:'جو', sound:'jo', meaning:'who'},
    {word:'نَو', sound:'nau', meaning:'nine'},
    {word:'بَس', sound:'bas', meaning:'enough'},
    {word:'دَس', sound:'das', meaning:'ten'},
    {word:'مِل', sound:'mil', meaning:'meet'},
    {word:'ہَم', sound:'hum', meaning:'we'},
    {word:'تُم', sound:'tum', meaning:'you (plural)'},
    {word:'دَم', sound:'dam', meaning:'breath'},
    {word:'رَب', sound:'rab', meaning:'lord'}
];

// Arabic Letters (28 letters with harakat and connection forms)
const ARABIC_LETTERS = [
    {letter:'ا', name:'alif', fatha:'أَ', kasra:'إِ', damma:'أُ', sf:'a', sk:'i', sd:'u', initial:'ا', medial:'ـا', final:'ـا'},
    {letter:'ب', name:'baa', fatha:'بَ', kasra:'بِ', damma:'بُ', sf:'ba', sk:'bi', sd:'bu', initial:'بـ', medial:'ـبـ', final:'ـب'},
    {letter:'ت', name:'taa', fatha:'تَ', kasra:'تِ', damma:'تُ', sf:'ta', sk:'ti', sd:'tu', initial:'تـ', medial:'ـتـ', final:'ـت'},
    {letter:'ث', name:'thaa', fatha:'ثَ', kasra:'ثِ', damma:'ثُ', sf:'tha', sk:'thi', sd:'thu', initial:'ثـ', medial:'ـثـ', final:'ـث'},
    {letter:'ج', name:'jeem', fatha:'جَ', kasra:'جِ', damma:'جُ', sf:'ja', sk:'ji', sd:'ju', initial:'جـ', medial:'ـجـ', final:'ـج'},
    {letter:'ح', name:'haa', fatha:'حَ', kasra:'حِ', damma:'حُ', sf:'ha', sk:'hi', sd:'hu', initial:'حـ', medial:'ـحـ', final:'ـح'},
    {letter:'خ', name:'khaa', fatha:'خَ', kasra:'خِ', damma:'خُ', sf:'kha', sk:'khi', sd:'khu', initial:'خـ', medial:'ـخـ', final:'ـخ'},
    {letter:'د', name:'daal', fatha:'دَ', kasra:'دِ', damma:'دُ', sf:'da', sk:'di', sd:'du', initial:'د', medial:'ـد', final:'ـد'},
    {letter:'ذ', name:'dhaal', fatha:'ذَ', kasra:'ذِ', damma:'ذُ', sf:'dha', sk:'dhi', sd:'dhu', initial:'ذ', medial:'ـذ', final:'ـذ'},
    {letter:'ر', name:'raa', fatha:'رَ', kasra:'رِ', damma:'رُ', sf:'ra', sk:'ri', sd:'ru', initial:'ر', medial:'ـر', final:'ـر'},
    {letter:'ز', name:'zaay', fatha:'زَ', kasra:'زِ', damma:'زُ', sf:'za', sk:'zi', sd:'zu', initial:'ز', medial:'ـز', final:'ـز'},
    {letter:'س', name:'seen', fatha:'سَ', kasra:'سِ', damma:'سُ', sf:'sa', sk:'si', sd:'su', initial:'سـ', medial:'ـسـ', final:'ـس'},
    {letter:'ش', name:'sheen', fatha:'شَ', kasra:'شِ', damma:'شُ', sf:'sha', sk:'shi', sd:'shu', initial:'شـ', medial:'ـشـ', final:'ـش'},
    {letter:'ص', name:'saad', fatha:'صَ', kasra:'صِ', damma:'صُ', sf:'sa', sk:'si', sd:'su', initial:'صـ', medial:'ـصـ', final:'ـص'},
    {letter:'ض', name:'daad', fatha:'ضَ', kasra:'ضِ', damma:'ضُ', sf:'da', sk:'di', sd:'du', initial:'ضـ', medial:'ـضـ', final:'ـض'},
    {letter:'ط', name:'taa', fatha:'طَ', kasra:'طِ', damma:'طُ', sf:'ta', sk:'ti', sd:'tu', initial:'طـ', medial:'ـطـ', final:'ـط'},
    {letter:'ظ', name:'dhaa', fatha:'ظَ', kasra:'ظِ', damma:'ظُ', sf:'dha', sk:'dhi', sd:'dhu', initial:'ظـ', medial:'ـظـ', final:'ـظ'},
    {letter:'ع', name:'ain', fatha:'عَ', kasra:'عِ', damma:'عُ', sf:'a', sk:'i', sd:'u', initial:'عـ', medial:'ـعـ', final:'ـع'},
    {letter:'غ', name:'ghain', fatha:'غَ', kasra:'غِ', damma:'غُ', sf:'gha', sk:'ghi', sd:'ghu', initial:'غـ', medial:'ـغـ', final:'ـغ'},
    {letter:'ف', name:'faa', fatha:'فَ', kasra:'فِ', damma:'فُ', sf:'fa', sk:'fi', sd:'fu', initial:'فـ', medial:'ـفـ', final:'ـف'},
    {letter:'ق', name:'qaaf', fatha:'قَ', kasra:'قِ', damma:'قُ', sf:'qa', sk:'qi', sd:'qu', initial:'قـ', medial:'ـقـ', final:'ـق'},
    {letter:'ك', name:'kaaf', fatha:'كَ', kasra:'كِ', damma:'كُ', sf:'ka', sk:'ki', sd:'ku', initial:'كـ', medial:'ـكـ', final:'ـك'},
    {letter:'ل', name:'laam', fatha:'لَ', kasra:'لِ', damma:'لُ', sf:'la', sk:'li', sd:'lu', initial:'لـ', medial:'ـلـ', final:'ـل'},
    {letter:'م', name:'meem', fatha:'مَ', kasra:'مِ', damma:'مُ', sf:'ma', sk:'mi', sd:'mu', initial:'مـ', medial:'ـمـ', final:'ـم'},
    {letter:'ن', name:'noon', fatha:'نَ', kasra:'نِ', damma:'نُ', sf:'na', sk:'ni', sd:'nu', initial:'نـ', medial:'ـنـ', final:'ـن'},
    {letter:'ه', name:'haa', fatha:'هَ', kasra:'هِ', damma:'هُ', sf:'ha', sk:'hi', sd:'hu', initial:'هـ', medial:'ـهـ', final:'ـه'},
    {letter:'و', name:'waaw', fatha:'وَ', kasra:'وِ', damma:'وُ', sf:'wa', sk:'wi', sd:'wu', initial:'و', medial:'ـو', final:'ـو'},
    {letter:'ي', name:'yaa', fatha:'يَ', kasra:'يِ', damma:'يُ', sf:'ya', sk:'yi', sd:'yu', initial:'يـ', medial:'ـيـ', final:'ـي'}
];

const ARABIC_2LETTER = [
    {word:'أَبْ', sound:'ab', meaning:'father'},
    {word:'أُمْ', sound:'um', meaning:'mother'},
    {word:'يَدْ', sound:'yad', meaning:'hand'},
    {word:'فَمْ', sound:'fam', meaning:'mouth'},
    {word:'مَنْ', sound:'man', meaning:'who'},
    {word:'عَنْ', sound:'an', meaning:'about'},
    {word:'إِنْ', sound:'in', meaning:'if'},
    {word:'بَلْ', sound:'bal', meaning:'rather'},
    {word:'قَدْ', sound:'qad', meaning:'already'},
    {word:'هَلْ', sound:'hal', meaning:'is it?'}
];

const ARABIC_3LETTER = [
    {word:'كَتَبَ', sound:'kataba', meaning:'he wrote'},
    {word:'عَلِمَ', sound:'alima', meaning:'he knew'},
    {word:'فَتَحَ', sound:'fataha', meaning:'he opened'},
    {word:'جَلَسَ', sound:'jalasa', meaning:'he sat'},
    {word:'ذَهَبَ', sound:'dhahaba', meaning:'he went'},
    {word:'نَظَرَ', sound:'nadhara', meaning:'he looked'},
    {word:'سَمِعَ', sound:'samia', meaning:'he heard'},
    {word:'قَرَأَ', sound:'qaraa', meaning:'he read'},
    {word:'وَلَدْ', sound:'walad', meaning:'boy'},
    {word:'بِنْتْ', sound:'bint', meaning:'girl'}
];
