-- Regenerates sql/schema.sql from the live database.
--
-- Run it in the Supabase SQL editor (or through the MCP execute_sql tool),
-- then overwrite sql/schema.sql with the `schema_sql` value. The query is
-- read-only: it reads system catalogs, never application data.
--
-- `normalized_md5` lets you check a saved file matches the database. It is
-- the md5 of schema_sql after removing carriage returns, removing spaces and
-- tabs at the end of each line, and trimming trailing whitespace. Python:
--   re.sub(r'[ \t]+\n', '\n', s.replace('\r', '')).rstrip(' \t\n')

with
sections(sect, title) as (
  values
    (1, 'EXTENSIONS'),
    (2, 'TABLES'),
    (3, 'CONSTRAINTS'),
    (4, 'INDEXES'),
    (5, 'FUNCTIONS'),
    (6, 'TRIGGERS'),
    (7, 'ROW LEVEL SECURITY'),
    (8, 'POLICIES'),
    (9, 'FUNCTION PRIVILEGES')
),
objects(sect, sort_key, ddl) as (
  select 1, e.extname::text,
    'create extension if not exists ' || quote_ident(e.extname) || ' with schema ' || quote_ident(n.nspname) || ';'
  from pg_extension e
  join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'
  union all
  select 2, c.relname::text,
    'create table public.' || quote_ident(c.relname) || E' (\n' ||
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || case
           when a.attidentity = 'a' then ' generated always as identity'
           when a.attidentity = 'd' then ' generated by default as identity'
           when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
           when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
           else ''
         end
      || case when a.attnotnull then ' not null' else '' end,
      E',\n' order by a.attnum
    ) || E'\n);'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname
  union all
  select 3,
    case con.contype when 'p' then '1' when 'u' then '2' when 'c' then '3' when 'x' then '4' else '5' end
      || ':' || c.relname || ':' || con.conname,
    'alter table public.' || quote_ident(c.relname) || ' add constraint ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and con.contype in ('p', 'u', 'c', 'x', 'f')
  union all
  select 4, i.tablename || ':' || i.indexname, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (
      select 1 from pg_constraint con
      where con.conindid = (quote_ident(i.schemaname) || '.' || quote_ident(i.indexname))::regclass
    )
  union all
  select 5, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    rtrim(pg_get_functiondef(p.oid), E'\n') || ';'
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
  union all
  select 6, c.relname || ':' || t.tgname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
  union all
  select 7, c.relname::text,
    'alter table public.' || quote_ident(c.relname) || ' enable row level security;'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
  union all
  select 8, c.relname || ':' || pol.polname,
    'create policy ' || quote_ident(pol.polname) || ' on public.' || quote_ident(c.relname)
    || case when pol.polpermissive then '' else ' as restrictive' end
    || ' for ' || case pol.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end
    || ' to ' || (
         select string_agg(case when r.role_oid = 0 then 'public' else quote_ident(pg_get_userbyid(r.role_oid)) end, ', ' order by r.role_oid)
         from unnest(pol.polroles) as r(role_oid)
       )
    || coalesce(E'\n  using (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '')
    || coalesce(E'\n  with check (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '')
    || ';'
  from pg_policy pol
  join pg_class c on c.oid = pol.polrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
  union all
  select 9, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    '-- ' || p.oid::regprocedure::text || E'\n--   acl: ' || coalesce(p.proacl::text, '(default: EXECUTE granted to PUBLIC)')
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
),
assembled as (
  select
    E'-- Tiny Thinkers — production database schema (public)\n'
    || '-- Generated ' || current_date::text || E' by sql/dump_schema.sql. Do not hand-edit:\n'
    || E'-- change the database through sql/migrations/, then regenerate this file.\n\n'
    || string_agg(section_text, E'\n\n' order by sect) || E'\n' as schema_sql
  from (
    select s.sect,
      E'-- =====================================================================\n-- '
        || s.title
        || E'\n-- =====================================================================\n\n'
        || coalesce(string_agg(o.ddl, E'\n\n' order by o.sort_key), '-- (none)') as section_text
    from sections s
    left join objects o on o.sect = s.sect
    group by s.sect, s.title
  ) per_section
)
select
  schema_sql,
  length(schema_sql) as chars,
  md5(rtrim(regexp_replace(replace(schema_sql, E'\r', ''), E'[ \t]+\n', E'\n', 'g'), E' \t\n')) as normalized_md5
from assembled;
